#!/bin/bash
# =============================================================================
# PGVectorRAGIndexer — Server Setup Script
# =============================================================================
#
# Sets up the PGVectorRAGIndexer backend server (DB + API) on a headless
# Linux, macOS, or NAS machine.  Desktop clients connect remotely.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/valginer0/PGVectorRAGIndexer/main/server-setup.sh | bash
#
# Or clone first and run locally:
#   git clone https://github.com/valginer0/PGVectorRAGIndexer.git
#   cd PGVectorRAGIndexer
#   bash server-setup.sh [OPTIONS]
#
# Options:
#   --port PORT         API port (default: 8000)
#   --data-dir DIR      Directory for persistent data (default: ./data)
#   --no-start          Configure only, don't start containers
#   --generate-key      Auto-generate an API key and print it
#
# Requirements:
#   - Docker + Docker Compose v2
#   - Port 8000 (or custom) available
#   - No Python required on the server (everything runs in Docker)
# =============================================================================

set -e

# ── Defaults ─────────────────────────────────────────────────────────────────
API_PORT="${API_PORT:-8000}"
DATA_DIR=""
NO_START=false
GENERATE_KEY=false

# ── Colors ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ── Parse arguments ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --port)       API_PORT="$2"; shift 2 ;;
        --data-dir)   DATA_DIR="$2"; shift 2 ;;
        --no-start)   NO_START=true; shift ;;
        --generate-key) GENERATE_KEY=true; shift ;;
        -h|--help)
            head -28 "$0" | tail -25
            exit 0
            ;;
        *) echo -e "${RED}Unknown option: $1${NC}"; exit 1 ;;
    esac
done

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║       PGVectorRAGIndexer — Server Setup                   ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Prerequisites ───────────────────────────────────────────────────
echo -e "${GREEN}[1/5] Checking prerequisites...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}✗ Docker not found.${NC}"
    echo -e "${YELLOW}  Install: https://docs.docker.com/engine/install/${NC}"
    exit 1
fi
echo -e "  ✓ Docker: $(docker --version | head -1)"

# Check Docker Compose v2
if docker compose version &> /dev/null; then
    echo -e "  ✓ Docker Compose: $(docker compose version --short 2>/dev/null || echo 'v2')"
elif command -v docker-compose &> /dev/null; then
    echo -e "${YELLOW}  ⚠ Found docker-compose (v1). Docker Compose v2 recommended.${NC}"
else
    echo -e "${RED}✗ Docker Compose not found.${NC}"
    exit 1
fi

# Check Docker daemon is running
if ! docker info &> /dev/null 2>&1; then
    echo -e "${RED}✗ Docker daemon is not running. Please start Docker first.${NC}"
    exit 1
fi
echo -e "  ✓ Docker daemon running"
echo ""

# ── Step 2: Determine project directory ─────────────────────────────────────
echo -e "${GREEN}[2/5] Setting up project directory...${NC}"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2>/dev/null && pwd )"

# If docker-compose.yml exists in current dir, use it
if [ -f "$SCRIPT_DIR/docker-compose.yml" ]; then
    PROJECT_DIR="$SCRIPT_DIR"
    echo -e "  Using existing project at: ${CYAN}$PROJECT_DIR${NC}"
elif [ -f "./docker-compose.yml" ]; then
    PROJECT_DIR="$(pwd)"
    echo -e "  Using existing project at: ${CYAN}$PROJECT_DIR${NC}"
else
    # Need to clone
    PROJECT_DIR="${HOME}/PGVectorRAGIndexer"
    if [ -d "$PROJECT_DIR/.git" ]; then
        echo -e "  Updating existing clone at: ${CYAN}$PROJECT_DIR${NC}"
        cd "$PROJECT_DIR"
        git pull origin main 2>/dev/null || true
    else
        echo -e "  Cloning to: ${CYAN}$PROJECT_DIR${NC}"
        git clone "https://github.com/valginer0/PGVectorRAGIndexer.git" "$PROJECT_DIR"
    fi
fi

cd "$PROJECT_DIR"
echo ""

# ── Step 3: Configure environment ───────────────────────────────────────────
echo -e "${GREEN}[3/5] Configuring environment...${NC}"

# Create .env if it doesn't exist
if [ ! -f ".env" ]; then
    if [ -f ".env.example" ]; then
        cp .env.example .env
    else
        cat > .env <<EOF
# PGVectorRAGIndexer Server Configuration
# Generated by server-setup.sh

POSTGRES_USER=rag_user
POSTGRES_PASSWORD=rag_password
POSTGRES_DB=rag_vector_db
API_HOST=0.0.0.0
API_PORT=${API_PORT}
PROJECT_DIR=${PROJECT_DIR}
EOF
    fi
    echo -e "  ✓ Created .env file"
else
    echo -e "  ${YELLOW}⚠ .env already exists, keeping current values${NC}"
fi

# Update API_PORT in .env
sed -i.bak "s|^API_PORT=.*|API_PORT=${API_PORT}|" .env 2>/dev/null || true
rm -f .env.bak

# Set up data directory for persistent volumes
if [ -n "$DATA_DIR" ]; then
    mkdir -p "$DATA_DIR"
    echo -e "  ✓ Data directory: ${CYAN}$DATA_DIR${NC}"
fi

echo -e "  ✓ API will listen on port ${CYAN}${API_PORT}${NC}"
echo ""

# ── Step 4: Start containers ────────────────────────────────────────────────
if [ "$NO_START" = true ]; then
    echo -e "${YELLOW}[4/5] Skipping container start (--no-start)${NC}"
else
    echo -e "${GREEN}[4/5] Starting containers...${NC}"

    # Use docker-compose.yml (has both db + app)
    if docker compose version &> /dev/null; then
        docker compose up -d
    else
        docker-compose up -d
    fi

    # Wait for API to be ready
    echo -e "  Waiting for API to be ready..."
    max_attempts=60
    attempt=0
    until curl -sf "http://localhost:${API_PORT}/api" > /dev/null 2>&1; do
        attempt=$((attempt + 1))
        if [ $attempt -eq $max_attempts ]; then
            echo -e "${YELLOW}  ⚠ API not responding yet. Check logs with: docker logs vector_rag_app${NC}"
            break
        fi
        sleep 2
        echo -n "."
    done
    echo ""

    if curl -sf "http://localhost:${API_PORT}/api" > /dev/null 2>&1; then
        echo -e "  ✓ API is running at ${CYAN}http://0.0.0.0:${API_PORT}${NC}"
    fi
fi
echo ""

# ── Step 5: Generate API key (optional) ─────────────────────────────────────
echo -e "${GREEN}[5/5] Post-setup...${NC}"

if [ "$GENERATE_KEY" = true ]; then
    echo -e "  Generating API key..."
    # The API key generation endpoint requires the API to be running
    if curl -sf "http://localhost:${API_PORT}/api" > /dev/null 2>&1; then
        KEY_RESPONSE=$(curl -sf -X POST "http://localhost:${API_PORT}/api/v1/api-keys" \
            -H "Content-Type: application/json" \
            -d '{"name": "server-setup-key"}' 2>/dev/null || echo "")
        if [ -n "$KEY_RESPONSE" ]; then
            echo -e "  ${GREEN}✓ API key generated. Save this — it won't be shown again:${NC}"
            echo -e "  ${CYAN}$KEY_RESPONSE${NC}"
        else
            echo -e "  ${YELLOW}⚠ Could not generate key. Create one manually via the API.${NC}"
        fi
    else
        echo -e "  ${YELLOW}⚠ API not running — start containers first, then generate a key.${NC}"
    fi
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              ✓ Server Setup Complete!                      ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Detect server IP
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
if [ -z "$SERVER_IP" ]; then
    SERVER_IP=$(ipconfig getifaddr en0 2>/dev/null || echo "<server-ip>")
fi

echo -e "${CYAN}Server URL for desktop clients:${NC}"
echo -e "  ${YELLOW}http://${SERVER_IP}:${API_PORT}${NC}"
echo ""
echo -e "${CYAN}Desktop client setup:${NC}"
echo -e "  1. Open the desktop app → Settings tab"
echo -e "  2. Switch to ${YELLOW}Remote Server${NC} mode"
echo -e "  3. Enter the server URL above"
echo -e "  4. Enter your API key"
echo ""
echo -e "${CYAN}Useful commands:${NC}"
echo -e "  View logs:       ${YELLOW}docker logs -f vector_rag_app${NC}"
echo -e "  Stop server:     ${YELLOW}docker compose down${NC}"
echo -e "  Restart:         ${YELLOW}docker compose restart${NC}"
echo -e "  Server-side CLI: ${YELLOW}docker exec -it vector_rag_app python indexer_v2.py --help${NC}"
echo ""
echo -e "${CYAN}Platform support:${NC}"
echo -e "  ✓ Linux (Docker)           — Primary target"
echo -e "  ✓ macOS (Docker Desktop)   — Supported"
echo -e "  ✓ Windows (WSL2 + Docker)  — Supported (see server-setup-wsl.sh)"
echo -e "  ~ NAS (Synology/QNAP)     — Best-effort, community-tested"
echo ""
