blank_issues_enabled: true
contact_links:
  - name: 📧 Direct Contact
    url: mailto:valginer0@gmail.com
    about: For commercial licensing, custom development, or private inquiries
  - name: 📚 Documentation
    url: https://github.com/valginer0/PGVectorRAGIndexer/blob/main/README.md
    about: Read the comprehensive documentation
  - name: 🚀 Quick Start Guide
    url: https://github.com/valginer0/PGVectorRAGIndexer/blob/main/QUICK_START.md
    about: Get started in 5 minutes
  - name: 📜 Licensing Information
    url: https://github.com/valginer0/PGVectorRAGIndexer/blob/main/LICENSING_SUMMARY.md
    about: Learn about dual licensing (Community + Commercial)
